- menu_name: "Navigation"

- name: "About"
  url: "/design/hi-everyone/"
  title: "About"

- name: "Booking"
  url: /services/"
  title: "Booking"

- name: "Shop"
  url: "https://www.etsy.com/shop/freethefoot/?etsrc=sdt"
  title: "Shop"

- name: "Blog Archive"
  url: "/blog/archive/"
  title: "Block Archive"